spring:
#  静态资源处理
  resources:
    add-mappings: true
    cache:
      cachecontrol:
        max-age: 3600
      chain:
        cache: true
        enabled: true
      static-locations: calsspath:/static/
# 启动资源链
  #        缓存相应时间，单位秒
  #    启动默认静态资源处理，默认启用
#  thymelaef配置
  thymeleaf:
#    关闭缓存
    cache: false
#    数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.233.56.74:3310/seckill?useUnicode=true&characterEndcoding=UTF-8&&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
#      连接池名
      pool-name: DateHikarip
#      最小连接数
      minimum-idle: 5
#      空闲链接存活量最大时间，默认10分钟
      idle-timeout: 180000
#      最大连接数，默认10
      maximum-pool-size: 10
#      从连接池返回的链接自动提交
      auto-commit: true
#      链接最大存活时间，0表示永久存活，默认1800000(30分钟)
      max-lifetime: 18000000
#      链接超时时间，默认30000(30秒)
      connection-timeout: 30000
#      测试链接是否可用的查询语句
      connection-test-query: SELECT 1

# redis数据库
  redis:
  #  服务器地址
#    host: 127.0.0.1
    host: 49.233.56.74
    port: 6100
  #  数据库
    database: 0
  #  超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #        最大连接数,默认为8
        max-active: 8
        #        最大连接阻塞等待时间,默认-1
        max-wait: 100000ms
#        最大空闲链接，默认8
        max-idle: 200
#        最小空闲链接，默认0
        min-idle: 5
# rabbit mq相关配置
  rabbitmq:
#    服务器
    host: 49.233.56.74
#    用户名
    username: guest
#    密码
    password: guest
    virtual-host: /
    port: 5673
    listener:
      simple:
#        消费者最小数量
        concurrency: 10
#        消费者最大数量
        max-concurrency: 10
#        限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
#        启动时是否默认启动容器，默认true
        auto-startup: true
#        被拒绝时，是否重新进入队列
        default-requeue-rejected: true
    template:
      retry:
#        发布重试，默认false
        enabled: true
#        重试时间，默认1000ms
        initial-interval: 1000
#        重试最大次数，默认3次
        max-attempts: 3
#        重试最大间隔时间，默认10000ms
        max-interval: 10000
#        重试的间隔乘数，比如配置2.0，第一次就等10s，第二次就等20s，第三次就等40s
        multiplier: 1


# mybatis配置
mybatis-plus:
#  配置mapper.xml文档
  mapper-locations: classpath*:mapper/*.xml
#  配置mybatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.xxxxx.seckill.entity
    #开启下划线转驼峰
    #开启返回map结果集的下划线转驼峰

#  打印日志，sql打印(方法接口所在的报，不是mapper.xml所在的包)
logging:
  level:
    com.xxxxx.seckill.mapper: debug

server:
  port: 8868
