spring:
#  thymelaef配置
  thymeleaf:
#    关闭缓存
    cache: false
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://210.30.97.238:3310/seckill?useUnicode=true&characterEndcoding=UTF-8&&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
#      连接池名
      pool-name: DateHikarip
#      最小连接数
      minimum-idle: 5
#      空闲链接存活量最大时间，默认10分钟
      idle-timeout: 180000
#      最大连接数，默认10
      maximum-pool-size: 10
#      从连接池返回的链接自动提交
      auto-commit: true
#      链接最大存活时间，0表示永久存活，默认1800000(30分钟)
      max-lifetime: 18000000
#      链接超时时间，默认30000(30秒)
      connection-timeout: 30000
#      测试链接是否可用的查询语句
      connection-test-query: SELECT 1

# mybatis配置
mybatis-plus:
#  配置mapper.xml文档
  mapper-locations: classpath*./mapper/*Mapper.xml
#  配置mybatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.xxxxx.seckill.pojo

#  打印日志，sql打印(方法接口所在的报，不是mapper.xml所在的包)
logging:
  level:
    com.xxxxx.seckill.mapper: debug
